# Generated by Django 5.2.11 on 2026-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
