# Generated by Django 5.2.11 on 2026-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(unique=True),
        ),
    ]
